apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjust-deploy
  labels:
    app: adjust-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adjust-label
  template:
    metadata:
      labels:
        app: adjust-label
    spec:
      containers:
      - name: nginx-containers
        image: harshar21/adjustrepo:5

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: adjust-label
spec:
  selector:
    app: adjust-label
  type: NodePort   
  ports:
  - nodePort: 31000   
    port: 80
    targetPort: 80  
